# Yarn configuration to prevent auto-updates
nodeLinker: node-modules

# Disable auto-updates
enableGlobalCache: false
enableImmutableInstalls: false

# Use exact versions
saveExact: true

# Network settings
networkTimeout: 60000
networkConcurrency: 8

# Registry settings
npmRegistryServer: "https://registry.npmjs.org"

# Security settings
enableStrictSsl: true
enableScripts: true

# Cache settings
cacheFolder: "./.yarn/cache"
